---
title: "QGIS perusteet kunnille"
author: "Gispo Suomi Oy."
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Peruskurssi kunnille QGIS-ohjelmiston perusteisiin"
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
        number_sections: false
documentclass: book
---

# QGIS perusteet kunnille

## Tervetuloa kurssille!

Tämän kurssin tarkoituksena on opastaa sinut QGIS-ohjelmiston käyttöön ja sen erilaisiin ominaisuuksiin. Muiden paikkatieto-ohjelmistojen käyttökokemus ei ole välttämätöntä koulutukseen osallistumiselle. Toki niistä on paljon hyötyä. Kysy rohkeasti opettajalta lisätietoja, jos käytetty terminologia tai joku muu asia jää epäselväksi.

**QGISin taustaa**

QGIS (alkuperäiseltä nimeltään Quantum GIS) on yhteisöllisesti kehitetty avoimen lähdekoodin paikkatieto-ohjelmisto. QGISin kehittäminen on alkanut heinäkuussa 2002, minkä jälkeen kehitystyöhön on osallistunut yli 150 sovelluskehittäjää. QGISin käyttäjämäärää on hyvin vaikea arvioida, sillä ohjelmistoa ei tarvitse rekisteröidä ja sitä voi jakaa edelleen vapaasti. Karkeasti arvioiden voidaan kuitenkin todeta, että QGIS-ohjelmiston eri versioilla on yli miljoona käyttäjää maailmanlaajuisesti. QGIS--ohjelmisto ja sen lisäosat muodostavat kattavan ohjelmistoperheen paikkatietojen keräämiseen, mallintamiseen, analysointiin, visualisointiin ja jakeluun. Tämän kurssin aikana käsittelemme vain murto-osaa QGISin kaikista toiminnallisuuksista.

**Miksi QGIS?**

Perimmäinen syy QGISin käyttöön on tietysti paikkatietoaineistojen hyödyntäminen. Paikkatietoja voi hyödyntää monilla avoimen ja suljetun lähdekoodin ohjelmistolla, mutta tässä muutamia perusteluja juuri QGIS-ohjelmiston käytölle:

- **QGIS on ilmainen**:
Voit ladata, asentaa ja käyttää QGISia ilman lisenssi- tai käyttömaksuja.

- **QGIS on vapaa**:
Jos tarvitset QGISiin lisää ominaisuuksia,
sinulla on täysi vapaus laajentaa ja muuttaa ohjelmistoa.
Voit muokata QGISiä itse ohjelmoimalla,
tai esimerkiksi rahoittaa uusien ominaisuuksien kehittämistä.

- **QGIS kehittyy jatkuvasti**:
QGISillä on laaja käyttäjä- ja kehittäjäyhteisö,
ja ohjelmistoon lisätään toiminnallisuutta
sekä uusia lisäosia nopealla vauhdilla.

- **QGIS taipuu helposti omiin tarpeisiin**:
Lisätoiminnallisuutta kaivatessa ei usein tarvitse alkaa kehittämään QGISiä.
Joku muu on todennäköisesti jo törmännyt samaan käyttötapaukseen,
ja voit jo olemassaolevien lisäosien avulla toteuttaa omia prosesseja tukevia toimintoja.

- **QGISin käyttöön löytyy tukea ja ohjeita**:
QGIS sisältää laajan avoimen dokumentaation,
ja koko ajan kasvava käyttäjäyhteisö myös auttaa mielellään uusia käyttäjiä.
Voit myös kysyä apua suoraan sovelluskehittäjiltä.

- **QGIS on järjestelmäriippumaton**:
Voit käyttää QGISiä Windows-, Linux- ja macOS-käyttöjärjestelmissä.

- **QGIS on saatavilla eri kielillä**:
QGISin käyttöliittymää ja dokumentaatiota käännetään jatkuvasti monille eri kielille,
esimerkiksi suomeksi ja ruotsiksi.

## Lukuohje

**Web-selaimessa** suoritettavat komennot on merkitty seuraavasti:

::: note-box
<http://localhost:8080/geoserver>
:::

**Komentorivillä** suoritettavat komennot on merkitty seuraavasti:

::: commandline-box
``` shell
sudo lsb_release -a
```
:::

**Tiedostojen sisältö** on esitetty seuraavasti:

::: file-content-box
#IPv4 local connections: #host all all 127.0.0.1/32 md5
:::

**HTML- ja CSS-koodit, SQL-komennot sekä Python-scriptit** on esitetty seuraavasti:

::: code-box
``` sql
SELECT version();
```
:::

**Kysymykset, lisätiedot ja vihjeet** on esitetty seuraavasti:

::: hint-box
Mistä löydät tietoa GeoServeristä?

GeoServerillä on omat kotisivut.

Psst! Tietoa GeoServeristä löydät internetistä.
:::

## Mistä lisätietoja?

Ohessa muutamia web-sivustoja, joista saat lisätietoja:

::: note-box
<http://www.qgis.org/>
:::

::: note-box
<http://docs.qgis.org/>
:::

::: note-box
<http://gis.stackexchange.com/>
:::

::: note-box
<http://www.osgeo.fi>
:::

## Virheet

Jos havaitset materiaalissa virheitä, pyydämme ilmoittamaan niistä kouluttajalle tai sähköpostilla osoitteeseen [info\@gispo.fi](mailto:info@gispo.fi){.email}.

## Lisenssi ja oikeudet

Nämä materiaalit on "QGIS perusteet kunnille" -kurssille kehittänyt Gispo Suomi Oy. Materiaalit on lisensoitu seuraavalla lisenssillä: [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)

## Materiaali PDF-muodossa

Voit ladata harjoitukset PDF-muodossa tästä linkistä:

::: note-box
[Harjoitukset PDF-muodossa](https://github.com/gispocoding/master-training-data/releases/download/GP007/GP007.pdf)
:::
