---
title: "Introduction to PostGIS"
author: "Gispo Ltd"   
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Introduction to typical PostGIS use cases."
output:
    bookdown::html_book:
        toc: true
        toc_depth: 2
        number_sections: true
        pandoc_args: ["--number-sections"]
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
      
documentclass: book
---

# 1. Introduction

Welcome to the exercise section of the course!

With these exercises you can learn how to use the PostGIS extension in the PostgreSQL database management system. Choose a topic from the panel to the left.

## 1.1 Training material license

These training materials have been published with the [Create Commons Attribution-NoDerivs 4.0](https://creativecommons.org/licenses/by-nd/4.0/) license.

Licenses for the data used in the exercises:

- airports.dat - downloaded from [Openflights](https://openflights.org/data.html). The airport data is in the public domain.
- [Natural Earth](https://www.naturalearthdata.com/) - Data is in the public domain. Used data sets are: airports, countries, railroads, capitals and rivers (1:10m). Most data sets have been modified to include only EU countries. Some data sets have been slightly modified (fields which are unnecessary in the training have been removed or changed and some overseas territories of countries have been deleted as they warped certain analysis results.
