---
title: "QGIS plugin development"
author: "Gispo Suomi Oy"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Developing plugins for QGIS using Python"
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
        number_sections: false
documentclass: book
---

# QGIS plugin development

## Welcome to the course!

The purpose of this course is to learn how the Python programming language
can be used with QGIS and how to develop plugins that can be used to
extend QGIS in many ways.

## Reading Guide

Commands to execute in a **web browser** are displayed as follows:

:::{.note-box}
http://localhost:8080/geoserver
:::

Commands to execute in a **command prompt/terminal** are displayed as follows:

::: commandline-box
``` bash
sudo lsb_release -a
```
:::

**File content** is displayed as follows:

:::{.file-content-box}
#IPv4 local connections:
#host all all 127.0.0.1/32 md5
:::

**HTML and CSS code, SQL- queries and Python-scripts** are displayed as follows:

:::{.code-box}
``` sql
SELECT version();
```
:::

**Questions, notes and hints** are displayed as follows:

:::{.hint-box}
Where do you find information about GeoServer? 

GeoServer has its own website.
:::


## Additional information

Here are a few helpful websites:

:::{.note-box} 
http://www.qgis.org/ 
:::
:::{.note-box}
http://docs.qgis.org/ 
:::
:::{.note-box}
http://gis.stackexchange.com/
:::
:::{.note-box}
http://www.osgeo.fi
:::


## Mistakes

If you notice mistakes in these course materials, we ask you to report either directly to the trainer or by email us at info@gispo.fi .

## License and permissions

These materials are developed for the "QGIS plugin development" course by Gispo Finland Ltd.
The materials are licensed under [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/) license.

## Download a PDF version of the material

You can download a PDF version of the material from this link:

::: note-box
[PDF version of the material](https://github.com/gispocoding/master-training-data/releases/download/GE01_eng/GE01_eng.pdf)
:::
