---
title: "Kartat ja taitot"
author: "Gispo Ltd."
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "QGISin perusteet karttojen tulostamisen ja taittojen hallinnan näkökulmasta"
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
        number_sections: false
documentclass: book
---

<!-- Harjoitukset -->

# Kartat ja taitot

## Tervetuloa kurssille!

Tämän kurssin tarkoituksena on oppia visualisoimaan aineistoja QGISillä monipuolisesti ja tehokkaasti. Kurssilla käydään läpi QGISin visualisointiominaisuuksia laajasti, jotta koulutettava pystyisi tekemään tarkoituksenmukaisia ja selkeitä karttatulosteita. Tavoitteena on ymmärtää QGISin visualisointityökalujen toimintaa ja saada rutiinia niiden käyttöön.

## Lukuohje

**Web-selaimessa** suoritettavat komennot on merkitty seuraavasti:

::: note-box
<http://localhost:8080/geoserver>
:::

**Komentorivillä** suoritettavat komennot on merkitty seuraavasti:

::: commandline-box
sudo lsb_release -a
:::

**Tiedostojen sisältö** on esitetty seuraavasti:

::: file-content-box
#IPv4 local connections: #host all all 127.0.0.1/32 md5
:::

**HTML- ja CSS-koodit, SQL-komennot sekä Python-scriptit** on esitetty seuraavasti:

::: code-box
SELECT version();
:::

**Kysymykset, lisätiedot ja vihjeet** on esitetty seuraavasti:

::: hint-box
Mistä löydät tietoa GeoServeristä?

GeoServerillä on omat kotisivut.

Psst! Tietoa GeoServeristä löydät internetistä.
:::

## Mistä lisätietoja?

Ohessa muutamia web-sivustoja, joista saat lisätietoja:

::: note-box
<http://www.qgis.org/>
:::

::: note-box
<http://docs.qgis.org/>
:::

::: note-box
<http://gis.stackexchange.com/>
:::

::: note-box
<http://www.osgeo.fi>
:::

## Virheet

Jos havaitset materiaalissa virheitä, niin pyydämme ilmoittamaan niistä kouluttajalle tai sähköpostilla [info\@gispo.fi-osoitteeseen](mailto:info@gispo.fi-osoitteeseen){.email}.

## Lisenssi ja oikeudet

Nämä materiaalit on "Kartat ja taitot"-kurssille kehittänyt Gispo Oy. Materiaalit on lisensoitu seuraavalla lisenssillä: [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)
