# Kappale 5: Kohteiden muokkaus - Field Calculator (Osa 2)

## Tehtävä 5.1

Tarkastele tieviiva-aineistoa. Laske ensimmäiseen prioriteettiluokkaan (```Tieluokka```) kuuluvien teiden yhteenlaskettu pituus.

**Aineisto**: ```tieviiva_lappi.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```sum()```- funktiota.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
sum(
	$length, group_by:="Tienumero", filter:="Tieluokka"='1'
	)
```
:::
:::

## Tehtävä 5.2

Tarkastele ```vaestoruudut.gpkg```- ja hallintoalueaineistoa. Luo hallintoalueaineistoon uusi attribuuttikenttä (```asukkaita```). Laske oman maakuntasi kunnissa asuvan väestön määrä.

**Aineistot**: 

- ```vaestoruudut.gpkg```
- ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```aggregate()```- funktiota.

- Tutki lausekkeen muodostajassa ```aggregate()```- funktion käyttöohjetta. Täydennä oikeat argumentit kolmelle ensimmäiselle argumentille.
- Käytä valinnaista **filter**- argumenttia. Hae ```attribute```- funktiolla hallintoalue- tason kuntanumeron sisältävä kentän arvo ja tarkista onko se yhtäsuuri kuin väestöruudut- tason kuntanumeron sisältävä kentän arvo.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
if(
	"Maaku_ni1" = 'Pohjanmaa', 
		aggregate(
			layer:='vaestoruudut', aggregate:='sum', expression:="vaesto", filter:=attribute(
				@parent,'Kunta'
				) = "KUNTA"
			), NULL)
```
:::
:::

## Tehtävä 5.3

Lataa otos Helsingin rakennusaineistosta (``` rakennukset_dem.gpkg ```) [tästä linkistä](https://drive.google.com/uc?export=download&id=1Wr2fvPNWA7ST09VcGYt6Qz-3sn5x2S-y). Tarkastele korkeusmalli- (```dem2m.tif```) ja lataamaasi rakennusaineistoa. Selvitä korkeusmallin pikselin arvo rakennusten painopisteissä.

**Aineistot**: 

- ```dem2m.tif```
- ```rakennukset_dem.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```raster_value()```- funktiota. Korkeusmalli on yksikanavainen rasteri.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
raster_value(
	'dem2m', 1, centroid($geometry)
	)
```
:::
:::

## Tehtävä 5.4

Käytä tehtävässä rasterilaskinta (Raster Calculator). Työkalu löytyy QGISin prosessointityökaluista.

Luokittele korkeusaineisto kahteen luokkaan, jotka kuvastavat suurin piirtein maa- ja merialueita. Korkeusmallissa pikselin arvo kertoo korkeuden meren pinnasta ja yksikkö on metrejä.

- Luokka 1: rasteritason pikselit, joiden korkeusarvo on alle 1.
- Luokka 2: loput pikselit.

**Aineisto**: ```dem2m.tif```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Rakenna lauseke paloittain. Lähde liikkeelle tästä:

```("dem2m@1" >= 1)```

- Mitä yllä oleva lauseke palauttaa?
- Yllä oleva lauseke liittyy luokkaan 2. Mitä voit lisätä lausekkeeseen, että ehdon täyttävät pikselit saavat arvon 2 tehtävänannon mukaisesti?
- Miten kirjoitat vastaavan lausekkeen luokalle 1?
- Miten yhdistät lausekkeet siten, että saadaan tehtävänannon mukainen lopputulos?
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
Lauseke:

::: code-box
``` sql
("dem2m@1" < 1) * 1 + ("dem2m@1" >= 1) * 2
```
:::
Käytä seuraavia asetuksia:

- Cell size: 2
- Output extent: klikkaa nuolesta -> Calculate from Layer -> dem2m
- Output CRS: EPSG:3067
- Output: tallenna .tif tiedostoon
:::

## Lisätehtävät

[Lisätehtävä 4](15_kappale_15.html#lisätehtävä-4)

[Lisätehtävä 5](15_kappale_15.html#lisätehtävä-5)

[Lisätehtävä 6](15_kappale_15.html#lisätehtävä-6)

[Lisätehtävä 7](15_kappale_15.html#lisätehtävä-7)