# Kappale 15: Lisätehtävät

## Lisätehtävä 1

Tarkastele Helsingin alueen väestöruutuaineistoa. Luo aineistoon uusi sarake ja anna sen nimeksi asukkaita_sca (datatyyppi: Decimal number). Uuden attribuuttikentän arvojen tulee kuvata sitä, miten suuri kunkin ruudun asukasmäärä on suhteessa pienimmän ja suurimman asukasmäärän omaavaan ruutuun. Skaalaa arvot välille [0,100].

**Aineisto**: ```HSY_vaesto2022_muok.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Lausekkeeseen tulee syöttää monta sisäkkäistä funktiota:

- Etsi lausekkeen muodostajasta funktio, jolla voit tehdä lineaarisen skaalauksen.
- Asukkaita-sarakkeen tietotyyppi on kokonaisluku. Se tulee muuttaa lausekkeessa desimaaliluvuksi. Millä funktiolla se onnistuu?
- Millä funktiolla saat selville sarakkeen suurimman ja pienimmän luvun?
- Käytä lopuksi ```round()```-funktiota. Miten saat tuloksen kahden desimaalin tarkkuudella?
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
round(
	scale_linear(
		to_real(
			"asukkaita"
			),
		minimum(
			"asukkaita"
			),
		maximum(
			"asukkaita"
			), 0, 100
		), 2
	)
```
:::
:::

## Lisätehtävä 2

Tarkastele hallintoalueaineistoa. Mikäli kunnalla on olemassa nimi vain yhdellä virallisella kielellä (Kunta_ni2- attribuuttikentän arvo on N_A), korvaa se sanalla ```Puuttuu```.

**Aineisto**: ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```if()```-ehtolausekefunktiota.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
if(
	"Kunta_ni2" = 'N_A', 'Puuttuu', "Kunta_ni2"
	)
```
:::
:::

## Lisätehtävä 3

Tarkastele Natura-alueaineistoa. Selvitä (**Field Calculatorin General** -ryhmän funktioiden avulla) montako kohdetta ko. karttataso sisältää.

**Aineisto**: ```natura_alueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```layer_property()```- ehtolausekefunktiota.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
layer_property(
	'natura_alueet', 'feature_count'
	)
```
:::
:::

## Lisätehtävä 4

Tarkastele maanjäristysaineistoa. Luo uusi attribuuttikenttä (tyyppi: Text (string)) ja anna sen nimeksi Location Country. Muodosta lauseke, jonka avulla uuden kentän arvo pystytään johtamaan Location Name -attribuuttikentän arvosta.

**Aineisto**: ```maanjaristykset.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Location Name -kentässä maan nimi sijaitsee ennen kaksoispistettä ```:```.

- ```substr()```-funktiolla saat "irroitettua" merkkijonosta osion. Argumenteiksi tulee syöttää merkkijonon lisäksi aloitus- ja lopetuskohdat irroitettavalle tekstille.
- Etsi ```strpos()```-funktiolla oikea lopetuskohta.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
substr(
	"Location Name", 0, strpos(
		"Location Name", ':'
		) - 1
	)
```
:::
:::

## Lisätehtävä 5

Selvitä sisältääkö kuhunkin Natura-alueeseen liittyvä päätös vesilakia. Luo uusi attribuuttikenttä, johon voit tallentaa selvittämäsi tiedon.

**Aineisto**: ```natura_alueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Luo lauseke paloittain:

- Käytä ```string_to_array()```-funktiota
- Käytä ```array_contains()```-funktiota
- Käytä ```eval()```-funktiota

:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
eval(
	array_contains(
		string_to_array(
			"VnPaatosTo"
			), 'vesilaki'
		)
	)
```
:::
:::

## Lisätehtävä 6

Ennen tätä tehtävää tehtävä 5.2 tulee olla tehtynä. Laske kunkin hallintoalueen asukasmäärän prosentuaalinen osuus koko tarkastelemasi maakunnan väestöstä ja tallenna se uuteen attribuuttikenttään.

**Aineistot**: 

- ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
```sum()```-funktiolla voit laskea ```asukkaita```-sarakkeen yhteenlasketun määrän.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
( "asukkaita" / sum(
	"asukkaita"
	)
) * 100.0
```
:::
:::

## Lisätehtävä 7

Selvitä mitkä hallintoaluepolygonit sijaitsevat korkeintaan 20 km:n etäisyydellä Vaasan lyseon lukiosta. Käytä **Field Calculatoria**, älä geoprosessointityökaluja!

**Aineistot**: 

- ```hallintoalueet.gpkg```
- ```oppilaitokset.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
- Hae Vaasan lyseon lukio -kohde ```get_feature()```-funktiolla.
- Hae kohteen geometria ```geometry()```-funktiolla.
- Luo hallintoaluekohteelle 20 km:n buffer.
- Millä funktiolla voit tarkistaa leikkaavatko (intersect) buffer ja lyseon lukion geometria?
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
intersects(
	buffer(
		$geometry, 20000
		), geometry(
		get_feature(
			'oppilaitokset', 'onimi', 'Vaasan lyseon lukio'
			)
		)
	)
```
:::
:::

## Lisätehtävä 8

Luo uusi sarake (nimi: tunnus, tyyppi: string) ja hyödynnä Quick Field Calculation -palkkia tuottaaksesi sarakkeen arvoksi FIN: \<kunkin kunnan kuntanumero\>.

**Aineisto**: ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
- Valitse päivitettäväksi kentäksi tunnus.
- Kirjoita lauseke-kenttään.
- Napsauta lopuksi Update all -painiketta
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
'FIN: ' || "Kunta"
```
:::
:::

## Lisätehtävä 9

Tarkastele väestöruutuaineistoa (älä koko tasoa, **Select features by area**). Kategorisoi aineisto sen mukaan, asuuko ruudussa paljon vai vähän sekä miehiä että naisia. Luo oma kategoria myös vaihtoehdolle, että tietoa ei ole saatavilla miehistä tai naisista.

**Aineisto**: ```vaestoruudut.gpkg (sen alijoukko)```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```CASE WHEN .. THEN```- rakennetta.

::: code-box
``` sql
CASE
WHEN ... (ei tietoa)
	THEN 'Tieto puuttuu'
WHEN ... (miehiä ja naisia 0-100)
	THEN 'Vähän molempia'
WHEN (miehiä yli 100, naisia 0-100)
	THEN 'Paljon miehiä, vähän naisia'
WHEN (naisia yli 100, miehiä 0-100)
	THEN 'Paljon naisia, vähän miehiä'
ELSE
	'Paljon molempia'
END
```
:::
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
CASE
WHEN ("MIEHET"=-1 or "NAISET"=-1)
	THEN 'Tieto puuttuu'
WHEN ("MIEHET">0 and "MIEHET"<100 and "NAISET">0 and "NAISET"<100)
	THEN 'Vähän molempia'
WHEN ("MIEHET">100 and "NAISET">0 and "NAISET"<100)
	THEN 'Paljon miehiä, vähän naisia'
WHEN ("NAISET">100 and "MIEHET">0 and "MIEHET"<100)
	THEN 'Paljon naisia, vähän miehiä'
ELSE
	'Paljon molempia'
END
```
:::
:::

## Lisätehtävä 10

Tarkastele rakennusaineistoa. Hyödynnä Geometry Generatoria ja luo nimiöinti, jonka avulla saadaan näkyviin jokaisen polygonin ulkorajan segmentin pituus. Ilmoita tämä luku yhden desimaalin tarkkuudella, jotta tieto mahtuu näkymään.

**Aineisto**: ```pikku_rakennukset.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql

-- Geometry Generator -tasolle
segments_to_lines(
	force_rhr(
		$geometry
		)
	)

-- Font marker -tasolle
format_number(
	length(
		geometry_n(
			$geometry, @geometry_part_num
			)
		), 1
	) || 'm'
```
:::
:::

## Lisätehtävä 11

Luo funktio, jonka avulla voidaan selvittää kolmen attribuuttikentän painotettu keskiarvo.

- Yksi luonnollinen käyttötapaus on laskea kolmen ikäryhmittäisen asukasluvun painotettu keskiarvo (esim. markkinoinnin kannalta työikäisillä ihmisillä on lapsia tai vanhuksia enemmän painoarvoa).
- Rajaa huomioitavat väestöruudut Select features by area -työkalulla!
- Funktion syötteet: kolme attribuuttikenttää, kolme painokerrointa

**Aineisto**: ```HSY_vaesto2022_muok.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
1. Luo painotettuka-niminen funktio Field Calculatorin Function Editor -välilehdellä.
- Muista painaa lopulta Save and Load functions -painiketta!
2. Mene hsy_vaesto2020_muok-tason Field Calculatoriin ja määritä uusi Decimal-kenttä.
3. Kirjoita ao. lauseke Expression-ikkunaan ja paina OK.

::: code-box
``` sql
painotettuka("ika10_19", "ika30_39", "ika70_79", 0.2, 0.7, 0.1)
```
:::
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
from qgis.core import *
from qgis.gui import *

@qgsfunction(args='auto', group='Custom', referenced_columns=[])
def painotettuka(field1, field2, field3, value1, value2, value3, feature, parent):
    """
    Finds out the weighted average of three columns.
    """

    # HSYn datassa arvo 99 = Tieto puuttuu, joten jos jokin kenttä sisältää tämän arvon,
    # painotetun keskiarvon laskeminen ei ole mielekästä
    if 99 in (field1, field2, field3):
        return NULL
    else:
        return value1 * field1 + value2 * field2 + value3 * field3
```
:::
:::

## Geoprosessointiesimerkki

Alta löytyy esimerkki yksinkertaisesta geoprosessointiskriptistä. Skripti muuttaa ```rautatieviiva_suomi.gpkg```-tason ```Sahkoistys```-sarakkeen arvot selkokieliseksi ja tallentaa tiedot uuteen CSV-taulukkotiedostoon. Voit kokeilla lisätä skriptin QGISiin ja ajaa sen.

**Aineisto:** ```rautatieviiva_suomi.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">geoprosessointiskripti</button>

::: hidden-box
::: code-box
``` python
from PyQt5.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFileDestination,
)

class SaveAttributesAlgorithm(QgsProcessingAlgorithm):
    """Saves the selected attribute fields values of a vector layer to a CSV file."""
    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def tr(self, string):
        """
        Returns a translatable string with the self.tr() function.
        """
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        # Must return a new copy of your algorithm.
        return SaveAttributesAlgorithm()

    def name(self):
        """
        Returns the unique algorithm name.
        """
        return 'savefeaturesascsv'

    def displayName(self):
        """
        Returns the translated algorithm name.
        """
        return self.tr('Save features as CSV')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to.
        """
        return self.tr('Example scripts')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs
        to.
        """
        return 'examplescripts'

    def shortHelpString(self):
        """
        Returns a localised short help string for the algorithm.
        """
        return self.tr('Saves selected features to a CSV file')
    
    def initAlgorithm(self, config=None):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )
        # We add a file output of type CSV.
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output File'),
                'CSV files (*.csv)',
            )
        )
    
    def processAlgorithm(self, parameters, context, feedback):
        source = self.parameterAsSource(parameters, self.INPUT, context)
        csv = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        fieldnames = [field.name() for field in source.fields()]
        # Compute the number of steps to display within the progress bar and get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()
        with open(csv, 'w') as output_file:
            # Write header
            line = ','.join(name for name in fieldnames if name=="Sahkoistys") + '\n'
            output_file.write(line)
            for current, f in enumerate(features):
                # Stop the algorithm if cancel button has been clicked
                if feedback.isCanceled():
                    break
                # Add a feature in the sink
                if f["Sahkoistys"]==1:
                    line = ','.join(str('Ei sahkoa') for name in fieldnames if name=="Sahkoistys") + '\n'
                else:
                    line = ','.join(str('Sahkoistetty') for name in fieldnames if name=="Sahkoistys") + '\n'
                output_file.write(line)
                # Update the progress bar
                feedback.setProgress(int(current * total))
        return {self.OUTPUT: csv}
```
:::
:::
