---
title: "QGIS-koulutus Kuopion vedelle"
author: "Gispo Oy."
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
abstract: "Tämä on QGIS-koulutus joka on räätälöity Kuopion Veden työntekijöille"
output:
    bookdown::html_book:
        toc: true
        theme: null
        template: custom.html
        css: custom.css
        split_by: rmd
        number_sections: false
documentclass: book
---

<!-- Harjoitukset -->

# QGIS-koulutus Kuopion vedelle

## Kurssimateriaalien lataaminen

Voit ladata harjoituksissa käytettävän kurssihakemiston tästä linkistä:

::: note-box
[Kurssihakemisto.zip](https://drive.google.com/file/d/1e--hPgLULVOJ5u25PJ-vywCPKhmWyHe0/view?usp=sharing)
:::

ja kurssin harjoitukset PDF-muodossa tästä linkistä:

::: note-box
[Harjoitukset PDF-muodossa](https://github.com/gispocoding/master-training-data/releases/download/GR005/GR005.pdf)
:::

## Lukuohje

**Web-selaimessa** suoritettavat komennot on merkitty seuraavasti:

::: note-box
<http://localhost:8080/geoserver>
:::

**Komentorivillä** suoritettavat komennot on merkitty seuraavasti:

::: commandline-box
``` bash
sudo lsb_release -a
```
:::

**Tiedostojen sisältö** on esitetty seuraavasti:

::: file-content-box
#IPv4 local connections: #host all all 127.0.0.1/32 md5
:::

**HTML- ja CSS-koodit, SQL-komennot sekä Python-scriptit** on esitetty seuraavasti:

::: code-box
``` sql
SELECT version();
```
:::

**Kysymykset, lisätiedot ja vihjeet** on esitetty seuraavasti:

::: hint-box
Mistä löydät tietoa GeoServeristä?

GeoServerillä on omat kotisivut.

Psst! Tietoa GeoServeristä löydät internetistä.
:::

## Mistä lisätietoja?

Ohessa muutamia web-sivustoja, joista saat lisätietoja:

::: note-box
<http://www.qgis.org/>
:::

::: note-box
<http://docs.qgis.org/>
:::

::: note-box
<http://gis.stackexchange.com/>
:::

::: note-box
<http://www.osgeo.fi>
:::

## Virheet

Jos havaitset materiaalissa virheitä, niin pyydämme ilmoittamaan niistä kouluttajalle tai sähköpostilla [info\@gispo.fi-osoitteeseen](mailto:info@gispo.fi-osoitteeseen){.email}.

## Lisenssi ja oikeudet

Nämä materiaalit on "QGIS-koulutus Kuopion vedelle"- kurssille kehittänyt Gispo Suomi Oy. Materiaalit on lisensoitu seuraavalla lisenssillä: [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)
