# 2. Missä kaikkialla QGISissä voi käyttää lausekkeita?

## Tehtävä 2.1

Tarkastele hallintoalueaineistoa. Luo uusi attribuuttikenttä (boolean), joka pitää sisällää tiedon siitä, sijaitseeko hallintoalue 50 km:n säteellä Helsingistä. Laske etäisyys polygonien painopisteiden välillä (centroid).

**Aineisto**: ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Luo lauseke pala palalta.

- Hae Helsinki-kohde (```get_feature()```- funktio)
- Hae Helsinki-kohteen geometria (```geometry()```- funktio)
- Laske Helsingin geometrialle painopiste (```centroid```- funktio)
- Lausekkeen muodostaja suorittaa lausekkeen jokaiselle kohteelle. Miten viittaat lausekkeessa tällä hetkellä käsiteltävän kohteen geometriaan?
- Laske tällä hetkellä käsiteltävälle geometrialla painopiste.
- Millä funktiolla saat laskettua etäisyyden? Laske Helsingin geometrian ja tällä hetkellä käsiteltävän geometrian painopisteiden välinen etäisyys.
- Tarkista onko etäisyys alle 50 km. Huomioi yksikkö!
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
distance(
	centroid(
		$geometry
		), centroid(
		geometry(
			get_feature(
				'hallintoalueet', 'Kunta_ni1', 'Helsinki'
				)
			)
		)
	) < '50000'
```
:::
:::




## Tehtävä 2.2

Tarkastele tieviiva-aineistoa. Laske ensimmäiseen prioriteettiluokkaan (```Tieluokka```) kuuluvien teiden yhteenlaskettu pituus.

**Aineisto**: ```tieviiva_lappi.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```sum()```- funktiota.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
sum(
	$length, group_by:="Tienumero", filter:="Tieluokka"='1'
	)
```
:::
:::

## Tehtävä 2.5

Tarkastele ```vaestoruudut.gpkg```- ja hallintoalueaineistoa. Luo hallintoalueaineistoon uusi attribuuttikenttä (```asukkaita```). Laske oman maakuntasi kunnissa asuvan väestön määrä.

**Aineistot**: 

- ```vaestoruudut.gpkg```
- ```hallintoalueet.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```aggregate()```- funktiota.

- Tutki lausekkeen muodostajassa ```aggregate()```- funktion käyttöohjetta. Täydennä oikeat argumentit kolmelle ensimmäiselle argumentille.
- Käytä valinnaista **filter**- argumenttia. Hae ```attribute```- funktiolla hallintoalue- tason kuntanumeron sisältävä kentän arvo ja tarkista onko se yhtäsuuri kuin väestöruudut- tason kuntanumeron sisältävä kentän arvo.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
if(
	"Maaku_ni1" = 'Pohjanmaa', 
		aggregate(
			layer:='vaestoruudut', aggregate:='sum', expression:="vaesto", filter:=attribute(
				@parent,'Kunta'
				) = "KUNTA"
			), NULL)
```
:::
:::

## Tehtävä 2.6

Lataa otos Helsingin rakennusaineistosta (``` rakennukset_dem.gpkg ```) [tästä linkistä](https://drive.google.com/uc?export=download&id=1Wr2fvPNWA7ST09VcGYt6Qz-3sn5x2S-y). Tarkastele korkeusmalli- (```dem2m.tif```) ja lataamaasi rakennusaineistoa. Selvitä korkeusmallin pikselin arvo rakennusten painopisteissä.

**Aineistot**: 

- ```dem2m.tif```
- ```rakennukset_dem.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Käytä ```raster_value()```- funktiota. Korkeusmalli on yksikanavainen rasteri.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
raster_value(
	'dem2m', 1, centroid($geometry)
	)
```
:::
:::

## Tehtävä 2.7

Käytä tehtävässä rasterilaskinta (Raster Calculator). Työkalu löytyy QGISin prosessointityökaluista.

Luokittele korkeusaineisto kahteen luokkaan, jotka kuvastavat suurin piirtein maa- ja merialueita. Korkeusmallissa pikselin arvo kertoo korkeuden meren pinnasta ja yksikkö on metrejä.

- Luokka 1: rasteritason pikselit, joiden korkeusarvo on alle 1.
- Luokka 2: loput pikselit.

**Aineisto**: ```dem2m.tif```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Rakenna lauseke paloittain. Lähde liikkeelle tästä:

```("dem2m@1" >= 1)```

- Mitä yllä oleva lauseke palauttaa?
- Yllä oleva lauseke liittyy luokkaan 2. Mitä voit lisätä lausekkeeseen, että ehdon täyttävät pikselit saavat arvon 2 tehtävänannon mukaisesti?
- Miten kirjoitat vastaavan lausekkeen luokalle 1?
- Miten yhdistät lausekkeet siten, että saadaan tehtävänannon mukainen lopputulos?
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
Lauseke:

::: code-box
``` sql
("dem2m@1" < 1) * 1 + ("dem2m@1" >= 1) * 2
```
:::
Käytä seuraavia asetuksia:

- Cell size: 2
- Output extent: klikkaa nuolesta -> Calculate from Layer -> dem2m
- Output CRS: EPSG:3067
- Output: tallenna .tif tiedostoon
:::

## Lisätehtävät

## Tehtävä 2.3

Tarkastele otosta Helsingin rakennusaineistosta. Huomioi, että valmistumispäivämäärä (```valm_pvm```- sarake) on ilmoitettu aineistossa teksti-datatyyppinä. Osassa kohteissa sarake sisältää myös ajankohdan ja päivämäärä on silloin ilmoitettu eri formaatissa. Luo uusi päivämääräsarake (esim. ```pvm_uusi```, datatyyppi Date), jossa rakennusten valmistumispäivämäärän ilmoitusmuoto on yhtenäistetty muotoon dd.MM.yyyy ja laske sen avulla uuteen sarakkeeseen (esim. ```rakennus_ika```) kuinka vanhoja rakennukset ovat (tähän päivään verrattuna).

**Aineisto**: ```pikku_rakennukset.gpkg```

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
Prosessi tulee tehdä kahdessa vaiheessa.

**Vaihe 1**:

- Aineistossa on kaksi erilaista päivämäärän esitystapaa. Ne voi erottaa toisistaan esimerkiksi merkkijonon pituuden avulla. Millä funktiolla löydät merkkijonon pituuden?
- Toinen esitystapa vastaa ```Datetime```-datatyyppiä ja toinen ```Date```-datatyyppiä, mutta ne on kuitenkin tallennettu tekstinä. Millä funktioilla saat muutettua tekstin oikeisiin formaatteihin?
- Lopullisen formaatin tulee molemmissa tapauksissa olla ```Date```.
- Suorita muunnos ```Date```- formaattiin, eritellen kahden eri esitystavan muunnokset  ```ìf()```- ehtolausefunktiolla.

**Vaihe 2**:

Kun ```uusi_pvm```- sarake on luotu:

- Luo lausekkeessa käytettävä päivämäärämuuttuja ```make_date()```-funktiolla.
- Laske ```age()```- funktiolla tämän päivämäärän ja ```pvm_uusi```-arvon välinen aikaväli.
- ```age()```- funktio palauttaa tuloksen ```Interval``` (aikaväli)-muodossa.
- ```Interval```-arvo pitää ajaa vielä yhden funktion läpi. ```day()```-funktiolla saat rakennuksen iän päivinä, ```year()```-funktiolla vuosina jne.
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

::: hidden-box
::: code-box
``` sql
-- Vaihe 1
if(
	length(
		"valm_pvm"
		) > 10, to_date(
		to_datetime(
			"valm_pvm"
			)
		), to_date(
		"valm_pvm", 'dd.MM.yyyy'
		)
		)
-- Vaihe 2
day(
	age(
		make_date(
			yyyy,mm,dd    -- Täydennä tämänhetkinen päivämäärä
			), "pvm_uusi"
		)
	)
```
:::
:::

