# Kappale 7 PyQGIS skriptaus

Täsä kappaleessa käydään läpi lisää käyttätapoja PyQGISin osalta.

Avaa valmiiksi QGISin Python-konsoli ja koodieditori.

## Projektin tuominen

Projektin tuominen QGISin voidaan tehdä seuraavalla tavalla:

::: code-box
```python
data_dir = '<projektiedoston sijainti kovalevyllä>'

project = QgsProject.instance()
project_name = 'projektitiedostonimi.qgz'
project_path = os.path.join(data_dir, project_name)
project.read(project_path)
```
:::

## Harjoitus 7.1

Tuo oma QGIS-projektisi QGISiin yllä olevan koodin avulla. 

## Tason lisääminen

Uuden tason voi lisätä seuraavalla tavalla.

::: code-box
```python
path = "<polku tiedostolle>"
# lisätään tasonimi loppuun
gpkg_layer = path + "|layername=<tasonimi>"
vlayer = QgsVectorLayer(gpkg_layer, "<Nimi tasolle>", "ogr")
if not vlayer.isValid():
    print("Taso ei ole valiidi!")
else:
    QgsProject.instance().addMapLayer(vlayer)
```
:::

## Harjoitus 7.2

Tuo taso QGISiin PyQGISin avulla. Yllä olevassa esimerkissä käytetään GeoPackagea, mutta jos haluat hakea jotain muuta niin pitää soveltaa.

[Täältä](https://docs.qgis.org/3.40/en/docs/pyqgis_developer_cookbook/loadlayer.html) saat apua!


## Vaihda tason nimeä

Jos haluat vaihtaa tason nimeä, voit tehdä sen käyttäen `.setName`. Alla olevassa esimerkissä muutetaan aktiivisen (eli valitun) tason nimeä.

::: code-box
```python
layer = iface.activeLayer()
name = layer.name()
layer.setName('<uusi nimi>')
```
:::

Jos haluat vaihtaa nimen tasolle joka on jo lisätty (etkä halua käyttää aktiivista tasoa) niin se tehdään näin:

::: code-box
```python
layer = QgsProject.instance().mapLayersByName("vanha_nimi")[0]
layer.setName("uusi_nimi")
```
:::

## Harjoitus 7.3

Vaihda jonkun tason nimeä käyttäen PyQGISiä.


## Tason tallentaminen

Opittiin aiemmin miten luodaan väliaikaisia tasoja. Nyt tarkoitus on luoda uusi taso sekä tallentaa se. Vaihda alla olevssa koodissa polku 

::: code-box
```python
# Luodaan uusi vektoritaso
vl = QgsVectorLayer("Point?crs=EPSG:3879", "rautatieasemat", "memory")
pr = vl.dataProvider()  # dataprovider antaa muokata taso ilman, että ollaan muokkaustilassa

pr.addAttributes([QgsField("nimi", QVariant.String)])
vl.updateFields()

f = QgsFeature(vl.fields())
f.setGeometry(QgsGeometry.fromWkt("POINT(25496724.80 6673126.03)"))
f["nimi"] = "Helsingin rautatieasema"
pr.addFeature(f)

# Tallennus levylle
out_path = "/polku/jonnekin/rautatieasemat.gpkg"  # oikea polku pitää lisätä
QgsVectorFileWriter.writeAsVectorFormat(
    vl, out_path, "UTF-8", vl.crs(), "GPKG"
)

# Ladataan GeoPackage projektiin
gpkg_layer = out_path + "|layername=rautatieasemat"
vlayer = QgsVectorLayer(gpkg_layer, "rautatieasemat", "ogr")

if not vlayer.isValid():
    print("Taso ei ole valiidi!")
else:
    QgsProject.instance().addMapLayer(vlayer)

```
:::
