# 8. Ratkaise ongelma työssäsi PyQGISin avulla

Luodaan omat funktiot/skriptit ja kokeillaan niiden ajamista QGISin Python-konsolissa. Yritetään luoda jotain omaa työtä helpottavaa. Voit pohtia työkaverin tai kouluttajan kanssa mikä voisi olla sopiva haaste.

Tämä tehtäväosio on varsin avoin ja voit itse miettiä, miten voisit sitä toteuttaa. Pohdi seuraavaa:

**Miten voin käyttää uusia taitojani hyödyksi omassa työssäni?**

**Minkä ongelman voisin ratkaista PyQGISillä?**

**Voinko automatisoida jotain, mitä teen usein?**

Jos koet, että tarvitset käyttää jotain prosessialgoritmia, eli jotain QGISin sisäänrakennettuja työkaluja niin lue vielä alla oleva osio.

## Prosessointialgoritmin kutsuminen

QGISiin voi kirjoittaa itsenäisiä prosessointialgoritmeja,
siten että ne kirjoitetaan omaan `.py`-tiedostoon ja lisätään
prosessointipaneeliin. .


Jos halutaan kutsua prosesointialgoritmia Pythonilla
konsolista, skriptistä, lisäosasta tai toisesta
prosessointialgoritmista, se voidaan tehdä seuraavasti.
`qgis.processing` tulee olla importoitu. Huomaa, että algoritmin
parametrit annetaan sanakirjana (dictionary), ja avaimina
käytetään algoritmissa määriteltyjä vakiomuuttujien arvoja.

Pidä valittuna esimerkiksi rautatieasema-tasoa ja aja alla oleva skripti. Mitä se tekee?

::: code-box
```python
# from qgis import processing

input_layer_id = iface.activeLayer().id()
parameters = {
    'INPUT': input_layer_id,
    'DISTANCE': 15,
    'SEGMENTS': 5,
    'END_CAP_STYLE': 0,
    'JOIN_STYLE': 0,
    'MITER_LIMIT': 2,
    'DISSOLVE': False,
    'OUTPUT': 'memory:'
}

output = processing.run('native:buffer', parameters)

# Huomioi, että `processing.run()` metodi
# palauttaa tässä sanakirjan.
# Tulostaso voidaan hakea avaimella 'OUTPUT'
buffered_layer = output.get('OUTPUT')

QgsProject.instance().addMapLayer(buffered_layer)
```
:::

