name: Update assets
on:
  repository_dispatch:
    types: [update-assets]

jobs:
  update-preview:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy modified assets to each directory
        run: ./update_assets.sh

      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "src/G* docs/G* template"
          message: "Automatic: Update assets"
