name: Update assets
on:
  push:
    branches:
      - main
    paths:
      - template/*.html
      - template/*.css
      - template/css/*
      - template/js/*

jobs:
  update-preview:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy modified assets to each directory
        run: ./update_assets.sh

      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "src/G*"
          token: ${{ secrets.GITHUB_TOKEN }}
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Automatic: Update assets from ${{ github.sha }}"

      - name: Dispatch render-deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update-assets
